development:
  adapter: postgresql
  database: harmony_hub_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: harmony_hub_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: harmony_hub_test
  pool: 5
  username:
  password:
